### ISSUE TITLE
Tidak ada halaman layanan.php

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#11]
Pada web anda ada layanan.html sementara layanan.php tidak ada. Jadi ketika berpindah halaman session nya tidak akan berpindah juga.

![bug 8](https://user-images.githubusercontent.com/53895082/66975142-be195480-f0c7-11e9-8664-f1247fc73fb5.jpg)

**Comment by donny1412** [comment]
tampilan website sudah berganti jadi fitur  tersebut sudah tidak ada lagi
<img width="960" alt="defense3" src="https://user-images.githubusercontent.com/55181699/67266824-4db16f80-f4db-11e9-8dc4-1a95871e042c.png">
<img width="960" alt="defense4" src="https://user-images.githubusercontent.com/55181699/67266826-4db16f80-f4db-11e9-9b88-a7562088b2b1.png">
