### ISSUE TITLE
Form bisa di kirim kosongan

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#12]
Pada halaman contacn.html form yang ada bisa dikirim dengan tanpa menginputkan kata-kata apapun.

![bug 9](https://user-images.githubusercontent.com/53895082/66975660-654abb80-f0c9-11e9-916a-d04eed0d39b6.jpg)

**Comment by Nisyua** [comment]
sudaaaa  makasyiii
