### ISSUE TITLE
Email kosong

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#13]
Pada halaman contact.html bagian bawah terdapat kolom untuk berlangganan yang dimana email tersebut bisa di dikirim walau tidak mengisi apa apa.

![bug 10](https://user-images.githubusercontent.com/53895082/66975734-9925e100-f0c9-11e9-82ff-3e9572b01ade.jpg)

**Comment by Nisyua** [comment]
![email](https://user-images.githubusercontent.com/50788092/67160439-d8c72400-f37a-11e9-90c4-6ba4e09cd686.png)
fixed
