### ISSUE TITLE
button dari berlangganan beberapa ga berfungsi

### ISSUE THREAD

**Issue by belladewusa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#14]
![Screenshot (103)](https://user-images.githubusercontent.com/55181780/66989757-2c254200-f0ef-11e9-9d11-916c236b948a.png)

**Comment by donny1412** [comment]
sudah fixed (ditambahkan required dan bisa dikirim)
<img width="960" alt="defense2" src="https://user-images.githubusercontent.com/55181699/67266214-da5b2e00-f4d9-11e9-91bf-c604b4ec702d.png">
