### ISSUE TITLE
matkul yang paling diminati ga berfungsi

### ISSUE THREAD

**Issue by belladewusa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#15]
![Screenshot (104)](https://user-images.githubusercontent.com/55181780/66990026-9fc74f00-f0ef-11e9-96f0-4d9eb23526d3.png)

**Comment by donny1412** [comment]
sudah tidak relevan karena tampilan website sudah berganti, fixed trims
<img width="960" alt="defense1" src="https://user-images.githubusercontent.com/55181699/67266116-923c0b80-f4d9-11e9-9fba-668d3a51b5a5.png">
