### ISSUE TITLE
Tidak bisa update password 

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#16]
Tidak bisa update password padahal di repository sudah ada file untuk update password.

![bug 1](https://user-images.githubusercontent.com/53895082/67002417-1111fc80-f106-11e9-8463-726f330de9dc.png)

**Comment by donny1412** [comment]
tampilan website sudah berganti sehingga fitur tersebut sudah tidak ada lagi
<img width="960" alt="defense4" src="https://user-images.githubusercontent.com/55181699/67266556-af250e80-f4da-11e9-9f77-26f6c7788f74.png">
