### ISSUE TITLE
Login tanpa perlu isi apa apa 

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#17]
form login.php begitu di tekan login dia langsung redirect ke index.php tanpa perlu memasukkan username dan password.

![Screen Shot 2019-10-17 at 9 01 10 PM](https://user-images.githubusercontent.com/53895082/67015868-6ad3f000-f121-11e9-8aad-f47bcc175259.png)

**Comment by Nisyua** [comment]
sudah
![login](https://user-images.githubusercontent.com/50788092/67280708-f7065e80-f4f7-11e9-932e-5d712b52186a.png)
![dah login](https://user-images.githubusercontent.com/50788092/67280710-f8378b80-f4f7-11e9-85cf-5ed49db4cc5f.png)
