### ISSUE TITLE
Register tanpa perlu isi apa apa 

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#18]
Pada halaman register jika tombol register di tekan maka dia akan langsung submit kosongan dan akan di record di dalam database 

![Screen Shot 2019-10-17 at 9 02 57 PM](https://user-images.githubusercontent.com/53895082/67015983-a078d900-f121-11e9-91bf-eeb2f2f94993.png)
![Screen Shot 2019-10-17 at 9 03 45 PM](https://user-images.githubusercontent.com/53895082/67015992-a66eba00-f121-11e9-9b96-a843fbe3b753.png)

**Comment by Bhaskaraa** [comment]
fixed bang
![Annotation 2019-10-22 181042](https://user-images.githubusercontent.com/49366063/67280421-5021c280-f4f7-11e9-937e-15ed436342d6.png)
![db](https://user-images.githubusercontent.com/49366063/67280472-70ea1800-f4f7-11e9-844e-e3bd29c8d8f5.png)

**Comment by Nisyua** [comment]
fixed
![Annotation 2019-10-22 181042](https://user-images.githubusercontent.com/50788092/67280599-b4dd1d00-f4f7-11e9-8dd8-d7e9f8314948.png)
![db](https://user-images.githubusercontent.com/50788092/67280609-b9a1d100-f4f7-11e9-9453-ed4340ee83cf.png)
