### ISSUE TITLE
Error pada login

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#19]
Jika kita memasukkan username dan password yang salah tidak ada pesan yang tampil untuk memberitahu bahwa username dan password salah. Halaman login hanya melakukan refresh jika username dan password salah.

![Screen Shot 2019-10-17 at 9 05 25 PM](https://user-images.githubusercontent.com/53895082/67016198-02d1d980-f122-11e9-88f9-bae3de0aeca3.png)

**Comment by Nisyua** [comment]
fixed.
![apaansi](https://user-images.githubusercontent.com/50788092/67097740-f19dd100-f1e4-11e9-9e31-37f861a4d404.png)
