### ISSUE TITLE
Masalah Link Page

### ISSUE THREAD

**Issue by DSlite** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#2]
Page Service masih belum terkoneksi dengan navbar. Mangat rek!!
![image](https://user-images.githubusercontent.com/17781660/66972975-9f638f80-f0c0-11e9-8013-f4322a4b16d0.png)

**Comment by donny1412** [comment]
page service sudah dihilangkan dan tampilan website sudah berganti, fixed trims
<img width="960" alt="defense3" src="https://user-images.githubusercontent.com/55181699/67266303-18585200-f4da-11e9-8adc-e001c1199e46.png">
