### ISSUE TITLE
Nama pemateri

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#20]
Ketika nama pemateri di halaman index.html di tekan maka halaman akan melakukan refresh dan tidak berpindah ke halaman tertentu.

![Screen Shot 2019-10-17 at 9 07 55 PM](https://user-images.githubusercontent.com/53895082/67016370-4a586580-f122-11e9-9b85-c05b61f1dab5.png)

**Comment by donny1412** [comment]
sudah dirubah agar tidak bisa diklik karena memang bukan merupakan fitur lagi, trims
<img width="960" alt="defense1" src="https://user-images.githubusercontent.com/55181699/67266007-599c3200-f4d9-11e9-9836-7aba791accbd.png">
