### ISSUE TITLE
tulisan fisika, kimia, matematika bisa di klik namun tidak direct kemanapun

### ISSUE THREAD

**Issue by lumbricina** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#23]
ada di index dan layanan
<img width="836" alt="Capture" src="https://user-images.githubusercontent.com/55181574/67172785-e1edda80-f3e6-11e9-8be0-bce58ce774bb.PNG">

**Comment by donny1412** [comment]
sudah di fix jadi tidak bisa diklik trims
<img width="960" alt="defense1" src="https://user-images.githubusercontent.com/55181699/67265807-db3f9000-f4d8-11e9-865e-5359d208480f.png">
