### ISSUE TITLE
check.php

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#24]
![image](https://user-images.githubusercontent.com/49645946/67193393-6e1bf400-f41f-11e9-8c12-a1d03c01c8d7.png)

**Comment by donny1412** [comment]
check sudah dihapus, terima kasih mas mikail
<img width="960" alt="defense4" src="https://user-images.githubusercontent.com/55181699/67266417-6a00dc80-f4da-11e9-80c0-ee10e036bb91.png">
