### ISSUE TITLE
Password dalam bentuk plaintext

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#3]
Pada bagian database seharusnya password dalam bentuk hash dan bukan dalam bentuk plaintext karena sangat rawan. Jika menggunakan password dalam bentuk plaintext maka kemungkinan besar akan terjadi sniffing pada web anda.

![bug 1](https://user-images.githubusercontent.com/53895082/66973496-5a405d00-f0c2-11e9-906a-5dbf00cc7adc.jpg)

**Comment by Bhaskaraa** [comment]
![sql](https://user-images.githubusercontent.com/49366063/67175662-2da58180-f3f1-11e9-974a-7158800d2e49.png)
fixed.
