### ISSUE TITLE
Habis login kok harus login lagi :v

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#4]
Setelah melakukan login dan berpindah ke halaman index.html yang disayangkan adalah kenapa tulisan login masih tetap tulisan login. Seharusnya tulisan login diganti dengan username.

![bug 2](https://user-images.githubusercontent.com/53895082/66973733-10a44200-f0c3-11e9-8ab7-b388f6d94ffd.jpg)

**Comment by Nisyua** [comment]
suda diperbaiki thx
