### ISSUE TITLE
Recursive login

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#5]
Pada saat telah melakukan login dan tombol login di tekan lagi maka kita harus login lagi. Seharusnya tombol login bisa di ganti dengan username atau dengan tombol logout dan bukan melakukan recursive login function

![bug 3](https://user-images.githubusercontent.com/53895082/66973881-80b2c800-f0c3-11e9-8d4b-837638f99b09.jpg)

**Comment by Nisyua** [comment]
sudah diperbaiki
