### ISSUE TITLE
Belum ada page single.html

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#7]
Pada bagian index.php terdapat matkul yang paling diminati namun pada saat di tekan link tersebut berpindah ke single.html dimana halaman single.html itu sendiri belum ada

![bug 5](https://user-images.githubusercontent.com/53895082/66974111-53b2e500-f0c4-11e9-8d10-c3ef05d7489a.jpg)

**Comment by donny1412** [comment]
tampilan website sudah berganti sehingga single.html tidak ada lagi dalam project kami, terima kasih 
<img width="960" alt="defense4" src="https://user-images.githubusercontent.com/55181699/67266681-f9a68b00-f4da-11e9-8b45-f7fdd3dd9e3e.png">
