### ISSUE TITLE
Email yang bisa di isi acak

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-quorush#8]
Pada bagian bawah dari index.html terdapat tempat untuk berlangganan dengan memasukkan email. Namun, kolom tersebut bisa di isi dengan alfabet acak.

![bug 6](https://user-images.githubusercontent.com/53895082/66974208-9f658e80-f0c4-11e9-88dd-fe10c558808d.jpg)

**Comment by Nisyua** [comment]
sudaaaaaaaaa
